FROM debian:latest
RUN apt update
RUN apt install -y vim curl systemctl
RUN curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
RUN apt install -y  mariadb-server mariadb-client
CMD ["/etc/init.d/mariadb", "start"]
