services:
  mariadb:
    build: requirements/mariadb/
    ports:
      - "2121:3306"
    user: mysql:mysql
    volumes: 
      - type: bind
        source: ../shared
        target: /world
        #source: /home/jrenau-v/data/database
        #target: /var/lib/mysql

  nginx:
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - type: bind
        #source: ../shared
        #target: /world
        source: /home/jrenau-v/data/webpage
        target: /var/www/html

  wordpress:
    build: requirements/wordpress
    depends_on:
      - mariadb
    ports:
      - "9999:9000"
    volumes:
      - type: bind
        #source: ../shared
        #target: /world
        source: /home/jrenau-v/data/webpage
        target: /var/www/html
