services:
  mariadb:
    build: requirements/mariadb/
    env_file: .env
    container_name: mariadb
    user: mysql:mysql
    ports:
      - "2121:3306"
    networks:
      - twikiland
    volumes:
      - mariadb_vol:/var/lib/mysql/

  nginx:
    build: requirements/nginx
    env_file: .env
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: /home/jrenau-v/data/webpage
        target: /var/www/html
    networks:
      - twikiland

  wordpress:
    build: requirements/wordpress
    env_file: .env
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - type: bind
        source: /home/jrenau-v/data/webpage
        target: /var/www/html
    networks:
      - twikiland

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/jrenau-v/data/database
      o: bind

networks:
    twikiland:
        driver: bridge
