services:
  mariadb:
    build: srcs/requirements/mariadb/
    ports:
      - "2121:3306"
  nginx:
    build: srcs/requirements/nginx/
    ports:
      - "4242:80"
  nginx2:
    build: srcs/requirements/nginx
