services:
#  mariadb:
#    build: srcs/requirements/mariadb/
#    ports:
#      - "2121:3306"
#    volume: 
#      - ./share:/world

  nginx:
    build: srcs/requirements/nginx
    ports:
      - "4242:80"
    volumes:
      - type: bind
        source: ./shared
        target: /world
  wordpress:
    build: srcs/requirements/wordpress
    ports:
      - "9999:9000"
    volumes:
      - type: bind
        source: ./shared
        target: /world
