services:
  mariadb:
    build: srcs/requirements/mariadb/
    ports:
      - "2121:3306"
    volumes: 
      - type: bind
        source: ./shared
        target: /world

  nginx:
    build: srcs/requirements/nginx
    ports:
      - "4242:80"
    volumes:
      - type: bind
        #source: ./shared
        #target: /world
        source: ./srcs/requirements/wordpress/webpage
        target: /var/www/html

  wordpress:
    build: srcs/requirements/wordpress
    ports:
      - "9999:9000"
    volumes:
      - type: bind
        #source: ./shared
        #target: /world
        source: ./srcs/requirements/wordpress/webpage
        target: /var/www/html
